version: "3"

services:

  redis_pubsub:
    build:
      context: .
      dockerfile: Dockerfile
    image: floorsheet-image
    container_name: worker
    depends_on:
      - postgres
      - redis
    env_file: ./src/floorsheet/.env
    restart: always
    volumes:
      - ./src:/src
    entrypoint:
      - python
      - /src/floorsheet/entrypoint/redis_eventconsumer.py

  api:
    image: floorsheet-image
    container_name: web
    depends_on:
      - redis_pubsub
      - postgres
    env_file: ./src/floorsheet/.env
    restart: always
    volumes:
      - ./src:/src

    command: "python3 ./floorsheet/entrypoint/main.py"
    ports:
      - "8000:8000"

  postgres:
    image: postgres:9.6
    env_file: ./src/floorsheet/.env
    container_name: floorsheet_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
